### ISSUE TITLE
Rate Limiting Clarification?

### ISSUE THREAD

**Issue by rbadi2020** [RTICWDT/open-data-maker#102]
Hello,
      Can the team clarify in terms of any rate limiting with respect to using this api: https://api.data.gov/ed/collegescorecard/v1/schools.json?

Observing this in the headers:

X-RateLimit-Limit →1000
X-RateLimit-Remaining →998

Is the X-RateLimit-Limit above **_per hour or per day?_** Please clarify and confirm.

**Comment by JAFrederick** [comment]
Hello,
The rate limiting is **per hour** and it is handled by the API authorization layer.

### Additional Information
- [Rate Limit Docs](https://api.data.gov/docs/rate-limits/)
- [General API Information](https://api.data.gov/docs/#general-information)
