### ISSUE TITLE
where to sign up for an api key?

### ISSUE THREAD

**Issue by gbinal** [RTICWDT/open-data-maker#17]
I may be missing it but on https://collegescorecard.ed.gov/data/documentation/ and https://github.com/RTICWDT/open-data-maker/blob/master/API.md, I'm not seeing where to sign up for an API key.  

Regardless of if I'm missing it or not, I'd suggest making it more prominent.

**Comment by brownpl** [comment]
You can sign up for an API key here: https://api.data.gov/signup/ - that key should work for all the data.gov APIs. 

I will forward your suggestion on to the content team. Thank you for taking the time to submit the issue.

**Comment by gbinal** [comment]
Just checking in on this again.  As best as I can tell, a developer coming to this API's documentation has no reasonable path to signing up for a key.  

The documentation really needs to be updated to link to that page or [embed it](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#embedding-the-api-key-signup-form-on-your-own-documentation-site).

**Comment by brownpl** [comment]
We just pushed an update to the production Scorecard [documentation site](https://collegescorecard.ed.gov/data/documentation/) that informs developers where they can sign up for a key. I am on the fence about adding it to the readme, as this application is intended for general use beyond the scorecard... though I notice the examples all reference the scorecard API! 

Anyway, we have a little progress on this for you! Thanks for following up.
