### ISSUE TITLE
Pulling from a specific dev_category

### ISSUE THREAD

**Issue by doug2mac** [RTICWDT/open-data-maker#36]
Is there a way to pull in the associated information for a specific dev_category in the query request?

Extending the example provided, if I wanted to pull the information located in only the 'school' dev_category for Boston College.

I have tried something similar to below, but get an invalid request:
https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=mykey&id=164924,dev_category=school

**Comment by brownpl** [comment]
If you download the [Data Dictionary](https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx), the dev_category is actually listed in Column B of the data_dictionary tab. So, you wanted to get the school name and the latitude and longitude, you would do:

https://api.data.gov/ed/collegescorecard/v1/schools?api_key=mykey&id=164924&fields=school.name,location.lat,location.lon

**Comment by doug2mac** [comment]
Thank you for the timely response. What I am wondering though is if the API has a function return __all__ fields from a specific dev-category. Say, for example I did not want just the school name, but all information that was within the school dev-category [school.name, school.city, school.state, etc.] same concept as returning all fields from a specific table in SQL in a school.* fashion.

**Comment by brownpl** [comment]
I'm afraid the API does not support wildcards selections as you describe. However, I would suggest you grab the full object (https://api.data.gov/ed/collegescorecard/v1/schools?api_key=mykey&id=164924) and then just keep the school object around for your needs. I will also make sure your request for wildcard selections is added to the request list for consideration for future development.
