### ISSUE TITLE
Unable to retrieve MD_EARN_WNE_P10 or other earnings data

### ISSUE THREAD

**Issue by DerekKaknes** [RTICWDT/open-data-maker#39]
Hi,

I've been building some queries against the API and cannot seem to get any values returned for earnings data.  I can pull back other Option Fields, but earnings fields always come back as 'None'.

Example: I query for NY 4yr schools in 2015 with several earnings fields.
```
https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=XXXXXXXX&school.degrees_awarded.predominant=3&school.main_campus=1&school.institutional_characteristics.level=1&school.state_fips=36&school.ownership=1&school.ownership=2&_fields=id%2Cschool.name%2C2015.earnings.6_yrs_after_entry.median%2C2015.earnings.8_yrs_after_entry.median_earnings%2C2015.earnings.10_yrs_after_entry.median%2C2015.earnings.6_yrs_after_entry.working_not_enrolled.mean_earnings%2C2015.earnings.8_yrs_after_entry.mean_earnings%2C2015.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings
```
And I get the following in response (filtered for relevance):
```js
{'2015.earnings.10_yrs_after_entry.median': None,
 '2015.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.6_yrs_after_entry.median': None,
 '2015.earnings.6_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.median_earnings': None,
 'id': 190150,
 'school.name': 'Columbia University in the City of New York'}
{'2015.earnings.10_yrs_after_entry.median': None,
 '2015.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.6_yrs_after_entry.median': None,
 '2015.earnings.6_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.median_earnings': None,
 'id': 194824,
 'school.name': 'Rensselaer Polytechnic Institute'}
{'2015.earnings.10_yrs_after_entry.median': None,
 '2015.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.6_yrs_after_entry.median': None,
 '2015.earnings.6_yrs_after_entry.working_not_enrolled.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.mean_earnings': None,
 '2015.earnings.8_yrs_after_entry.median_earnings': None,
 'id': 195030,
 'school.name': 'University of Rochester'}
```
As you can see, all of the earnings fields return `None`, even for schools that I can see have earnings data if I view them through the web ui or if I download the separate csv.  Am I constructing my queries incorrectly in some way?

Thanks

**Comment by kynetiv** [comment]
@DerekKaknes, Similar to this [stackexchange post](https://opendata.stackexchange.com/a/10889/10511), and somewhat clarified in [this one](https://opendata.stackexchange.com/a/7913/10511), the most recent earnings data available (currently) is in the 2013-14 data year, and would return none (or null) in later data files. Although I'm only a developer on this project (and don't understand the methodology around the data collection, etc.),  I'd say adjusting those earnings calls to be `2013.earnings.xxx` would return the values you're looking for.

**Comment by kynetiv** [comment]
Closing but feel free to reopen if you think there is still an issue here.
