### ISSUE TITLE
Faraday::TimeoutError: request timed out

### ISSUE THREAD

**Issue by gophry** [RTICWDT/open-data-maker#41]
Tried out with sample data and College score card raw data.
Using ubuntu 16.04 with rvm1.2.9/ruby 2.3.6 and branch dev
Elasticsearch is properly working with other applications but here a timeout.

WARNING! In Padrino >= 0.14.0 cli command padrino rake will NOT add
'./lib' folder to $LOAD_PATH. Please alter your require calls accordingly
if you depend on this behavior.
DEBUG - ETHON: Libcurl initialized
DEBUG -
DEBUG -
INFO - options: {:continue=>nil, :search=>"dictionary_only", :add_data=>nil, :only=>nil, :nest=>nil}
INFO - new_field_names: {"GEOID"=>"id", "ANSICODE"=>"code", "NAME"=>"name", "USPS"=>"state", "POP10"=>"population", "INTPTLAT"=>"location.lat", "INTPTLONG"=>"location.lon", "ALAND_SQMI"=>"land_area", "AWATER_SQMI"=>"area.water"}
INFO - additional_data
DEBUG - csv parsed
INFO - row 0: #<DataMagic::Index::Document:0x0000000008e3c030 @DaTa={"state"=>"NY", "id"=>"3651000", "code"=>"02395220", "name"=>"New York", "population"=>8175133, "land_area"=>302.643, "area"=>{"water"=>165.841}, "location"=>{"lat"=>40.664274, "lon"=>-73.9385}}, @id="New York">
DEBUG -
rake aborted!
Faraday::TimeoutError: request timed out

**Comment by gophry** [comment]
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:100:in `block in request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:127:in `each'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/operations.rb:35:in `finish'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `each'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `complete'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/ethon-0.10.1/lib/ethon/easy/operations.rb:33:in `perform'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/operations.rb:16:in `run'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/cacheable.rb:18:in `run'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/block_connection.rb:31:in `run'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/stubbable.rb:25:in `run'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/request/before.rb:26:in `run'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:72:in `call'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/home/XXXX/.rvm/gems/ruby-2.3.5/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/actions/index.rb:103:in `index'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/repository.rb:43:in `create'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/repository.rb:26:in `save'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/row_importer.rb:47:in `save'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/row_importer.rb:16:in `process'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/row_importer.rb:69:in `process'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:63:in `block in parse_csv_whole'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:62:in `parse_csv_whole'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:50:in `parse_csv'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:34:in `parse_and_log'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:15:in `process'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index/importer.rb:129:in `process'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:20:in `import_csv'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:49:in `block in index_with_dictionary'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:37:in `each'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:37:in `each_with_index'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:37:in `index_with_dictionary'
/home/XXXX/projects/university/open-data-maker/lib/data_magic/index.rb:72:in `import_with_dictionary'
/home/XXXX/projects/university/open-data-maker/tasks/import.rake:11:in `block in <top (required)>'
Tasks: TOP => import

**Comment by umar221b** [comment]
@gophry, did you manage to figure out what is wrong with this?

**Comment by gophry** [comment]
@umar221b to what i remember last that i had done was the following:
**RACK_ENV:** Can be either test or development. Development by default. Set this 
to 'test' if elasticsearch cluster doesn't have 3 or more nodes.

**Comment by umar221b** [comment]
@gophry,
Setting RACK_ENV to test worked. That will allow me to play with the app for now.
Thanks, mate. Appreciated.
