### ISSUE TITLE
Leading zeros dropping in JSON requests

### ISSUE THREAD

**Issue by doug2mac** [RTICWDT/open-data-maker#65]
I have noticed while accessing data via the API that for certain values, leading zeros (like those found in the ope6_id and ope8_id) are dropped from the resulting JSON. However, other values

Is there a way to keep this from happening?

Thank you

**Comment by doug2mac** [comment]
Hey @kynetiv,


Sure thing, I think that may be the issue as casting these values as integers (rather than strings) for these elements are truncating the 0's. Here are the first 3 values for `unitid` in the raw data extract from [here](https://collegescorecard.ed.gov/data/)
- I used the `MERGED_2016_17_PP.csv` in the below example.

|UNITID|OPEID|OPEID6|INSTNM|
|---|---|---|---|
|100654|00100200|001002|Alabama A & M University|
|100663|00105200|001052|University of Alabama at Birmingham|
|100690|02503400|025034|Amridge University|

The resulting json request from pulling those same 3 `unitid` values shows the following data for their respective data (query = 'https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key={mykey}&id={unitid}&_per_page=100'):

1. Unitid `100654`
   1. "ope8_id": 100200
   2.  "ope6_id": 1002
   3.  "id": 100654
2. Unitid `100663`
   1. "ope8_id": 105200
   2.  "ope6_id": 001052
   3.  "id": 100663
3. Unitid `100690`
   1. "ope8_id": 2503400
   2.  "ope6_id": 25034 
   3.  "id": 100690

Checking these `unitid` values against IPEDS via the following [link](https://nces.ed.gov/ipeds/datacenter/InstitutionByName.aspx?stepId=1) I see the full 8 and 6 digit values.

**Comment by kynetiv** [comment]
Thanks for the feedback. I've raised this issue internally and this will likely be resolved (cast to strings) in the next data refresh.

**Comment by kynetiv** [comment]
The College Scorecard API was updated on May 21, 2019 with a corrected data dictionary. The API now casts both `ope8_id` & `ope6_id` values as strings, which prevents the leading zeros from being dropped. Thanks again for the feedback @doug2mac !
