### ISSUE TITLE
Any API Limits?

### ISSUE THREAD

**Issue by umar221b** [RTICWDT/open-data-maker#69]
Hey,

I was not able to find any information about the API's limits. Are there any specific implemented limits before the user gets a 429 response?

Thank you.

**Comment by brownpl** [comment]
For the College Scorecard API, the default limit is 1,000 requests per hour. More information can be found here: https://api.data.gov/docs/rate-limits/.

**Comment by umar221b** [comment]
Thanks Patrick!
