### ISSUE TITLE
No way to get next page of results

### ISSUE THREAD

**Issue by rvi857** [RTICWDT/open-data-maker#79]
I'm using python's `requests` and `json` modules with the College Scorecard API. Whenever I try to include a "_page" field in my query, it gives a `JSONDecodeError` for any value of that parameter that isn't 0. If I try to request it via browser, it gives an internal server error.
  
For example:

`https://api.data.gov/ed/collegescorecard/v1/schools?fields=school.name,id,latest.aid.median_debt.completers.overall,latest.repayment.1_yr_repayment.completers,latest.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings` **works**

`https://api.data.gov/ed/collegescorecard/v1/schools?fields=school.name,id,latest.aid.median_debt.completers.overall,latest.repayment.1_yr_repayment.completers,latest.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings&_page=0` **works**

`https://api.data.gov/ed/collegescorecard/v1/schools?fields=school.name,id,latest.aid.median_debt.completers.overall,latest.repayment.1_yr_repayment.completers,latest.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings&_page=1`
**doesn't work**

**Comment by brownpl** [comment]
So sorry for the delay on this one! I think it slipped up into my inbox and I missed it. Anyway, for your last query, along the way, the need for the underscore was removed. So you can call additional pages using `page=1` or `page=2`. I tried your query dropping the underscore and it completed as expected for me.

**Comment by rvi857** [comment]
Hey! No worries, thanks. I think there's some kind of race condition because it occurs for me some times and not others.

**Comment by brownpl** [comment]
How much time do you estimate is elapsing between your requests?

**Comment by rvi857** [comment]
Wait actually nvm, I just tried it and there doesn't seem to be any gaps in
data. Thanks!

**Comment by brownpl** [comment]
Sweet. Happy developing!
