### ISSUE TITLE
How to get all of the Programs offered

### ISSUE THREAD

**Issue by BaileyFrederick** [RTICWDT/open-data-maker#82]
Is there a way to get all of the Latest.Academic info? I can't add latest.academics.program_percentage to the fields parameter but want to get back all of the program types without adding the specific program name.

**Comment by brownpl** [comment]
With the currently deployed version, this is not possible. Good news though - in an update coming later this month, wildcard searches like you are looking for will be possible. There will also be quite a bit more program-level data available. If you are curious, you can check out the preliminary debt data that is posted on the [data site](https://collegescorecard.ed.gov/data/preliminary/) to see if it might be interesting to you.

**Comment by vaMuchenje** [comment]
> Is there a way to get all of the Latest.Academic info? I can't add latest.academics.program_percentage to the fields parameter but want to get back all of the program types without adding the specific program name.

What program type are you referring to? Type of school or credential level? Can you give me a sample program type, so I can understand better.

**Comment by BaileyFrederick** [comment]
I am looking for a way to list all of the majors possibly covered in the api. For now I have just created a csv file of each "Major" such as program_percentage.agriculture. I want to automate this so that in the future if you change the name of a program it will handle that automatically. But there is no way to ask for all program_percentage fields.

**Comment by eday69** [comment]
@vaMuchenje Quick question. On your example query, if it was require to only extract credential.level=3 (Bachelor), how should I modify the query itself? Since this data is contained in an array?
Thanks !

**Comment by vaMuchenje** [comment]
> @vaMuchenje Quick question. On your example query, if it was require to only extract credential.level=3 (Bachelor), how should I modify the query itself? Since this data is contained in an array?
> Thanks !

What do you want to return? The credential level or something else based on a credential level?
As in, do you just want to filter results by credential level or you want to extract other info based on credential level?

**Comment by eday69** [comment]
Good question, I'm trying to figure out the correct way to extract/filter information from the API. So I guess my answer would be both! One could be, get the majors of a specific credential.level (3), and other would be to find (if exists) a specific major.
Thanks for the input !

**Comment by eday69** [comment]
Want to be able to access the title for credential.level=3 of a particular id, or, wishfully, find the ids, that have "xxx" title within the programs.cip_4_digits array.
Would this be possible or make sense?
