### ISSUE TITLE
New field of study data

### ISSUE THREAD

**Issue by BaileyFrederick** [RTICWDT/open-data-maker#89]
I'm looking to create a query that only returns back colleges that offer a specific major. So I want to be able to say "look at program.CIPcode.#### and make sure it is available. How should I go about this with the new info added? I am running into an error that says programs.cip_4_digit.code is unknown in this data set

**Comment by JAFrederick** [comment]
Hello,
I suggest updating your query with `latest.programs.cip_4_digit.code`.  We use a similar query for the College Scorecard front-end when searching for specific field of study data within institutions.

An example of such a query can be found here: https://collegescorecard.ed.gov/search/?cip4=1107&page=0&sort=completion_rate:desc  

The API query that powers that page looks something like: `https://api.data.gov/ed/collegescorecard/v1/schools?api_key=API_KEY&latest.programs.cip_4_digit.code=1107`  

It may be helpful to examine the network requests of that page within the browser developer tools (F12) and look for requests to `api.data.gov`.
