### ISSUE TITLE
How do I calculate Percent transferred within 2 years at original institution

### ISSUE THREAD

**Issue by gopala000** [RTICWDT/open-data-maker#93]
I need to find out percent transferred within 2 years at original institution. For completed (title_iv.completed_by.2yrs) and withdrawn (title_iv.withdrawn_by.2yrs), I see a single variable each returning data. 

For transfers should I add title_iv.transf_completed_4yr_by.2yrs, title_iv.transf_completed_2yr_by.2yrs, title_iv.transf_withdrawn_4yr_by.2yrs and title_iv.transf_withdrawn_2yr_by.2yrs? Or is it advisable to subtract sum of completed and withdrawn from title_iv.still_enrolled_by.2yrs to get the transferred number (assuming deaths are negligible)?

**Comment by JAFrederick** [comment]
Unfortunately the Scorecard data does not include metrics on students transferring within 2 years at the original institution.  The metrics you referenced are for students who transferred into an institution and then their outcomes (completed, withdrew, unknown) are reported when occurring within 2 years of transferring-in.  For additional information or questions, please feel free to email our help desk at Scorecarddata@rti.org
