### ISSUE TITLE
How to get specific cost information that are available in IPEDS data using API?

### ISSUE THREAD

**Issue by gopala000** [RTICWDT/open-data-maker#94]
I'd like to get some of the cost information like Typical room charge for academic year (ROOMAMT), Typical   board charge for academic year  (BOARDAMT). I couldn't find it in the API documentation. Is there a way to get it from API? Also is it possible to get student services info (STUSRV*) and sports association (ASSOC*) info via the API?

**Comment by JAFrederick** [comment]
Unfortunately, the IPEDS variables you are inquiring about are not included in the Scorecard datasets and thus not available via the Scorecard API.  For additional information or questions, please feel free to email our help desk at Scorecarddata@rti.org
