### ISSUE TITLE
dev-category root is not found

### ISSUE THREAD

**Issue by gopala000** [RTICWDT/open-data-maker#95]
I need to fetch latitutde & longitude. When I use root in the fields list, I get the error below. How do I workaround this?

```
    "errors": [
        {
            "error": "field_not_found",
            "input": "root",
            "message": "The input field 'root' (in the fields parameter) is not a field in this dataset."
        }
    ]
```

**Comment by JAFrederick** [comment]
Hello, Latitude and Longitude information is stored within the location object of each institution.

Here is an example query retrieving only the location object:
```
https://api.data.gov/ed/collegescorecard/v1/schools?
api_key=API_KEY
&fields=location
```

It might be helpful to take a look at the `institution_data_dictionary` sheet on the [data dictionary](https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx).  This will help bridge the gap between the data files and the API field names.  The column `NAME OF DATA ELEMENT` refers to the items in the data files and the `developer-friendly-name` is the API name.
