### ISSUE TITLE
Questions about API Key

### ISSUE THREAD

**Issue by WonChung** [RTICWDT/open-data-maker#98]
Our team is trying to use the College Scorecard API, are we allowed to request three API Keys and use them as a team or do we need to request private API Keys?

Also, do the API Keys expire?

**Comment by JAFrederick** [comment]
We do not handle the authorization portion of the application.  When registering for a key, a user is actually registering to use all Data.gov APIs.  I recommend reaching to data.gov using the contact form: https://api.data.gov/contact/
 
Some additional information that may be useful:
https://api.data.gov/docs/
https://api.data.gov/docs/api-key/
https://api.data.gov/docs/rate-limits/
